function preview_color_vectors(varargin)
%Preview color vectors generated by get_color_vectors. Elements 1 to 3 of
%the vector correspond to RGB intensities on a scale of 0 to 1,
%respectively. Anywhere between 1 to 3 color vectors can be previewed, each
%separated by a comma. Example: preview_color_vectors(He,DAB,Res)
if length(varargin)==1
    color_swatch=imresize(cat(3,varargin{1,1}(1),varargin{1,1}(2),varargin{1,1}(3)),100);
elseif length(varargin)==2
    color_swatch=[imresize(cat(3,varargin{1,1}(1),varargin{1,1}(2),varargin{1,1}(3)),100) imresize(cat(3,varargin{1,2}(1),varargin{1,2}(2),varargin{1,2}(3)),100)];
elseif length(varargin)==3
    color_swatch=[imresize(cat(3,varargin{1,1}(1),varargin{1,1}(2),varargin{1,1}(3)),100) imresize(cat(3,varargin{1,2}(1),varargin{1,2}(2),varargin{1,2}(3)),100) imresize(cat(3,varargin{1,3}(1),varargin{1,3}(2),varargin{1,3}(3)),100)];
end
imshow(color_swatch)
